# Generated by Django 5.0.14 on 2026-03-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_pagamento_conta_pagamento_movimento_gerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=True, help_text='Se marcado, gera movimento na tesouraria'),
        ),
    ]
