# Generated by Django 5.0.14 on 2026-03-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.area'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='congregacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.congregacao'),
        ),
    ]
