# Generated by Django 5.0.14 on 2026-03-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_alter_membro_area_alter_membro_congregacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacao',
            options={'verbose_name': 'Congregação', 'verbose_name_plural': 'Congregações'},
        ),
        migrations.AddField(
            model_name='membro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='cargo',
            field=models.CharField(choices=[('Membro', 'Membro'), ('Congregado', 'Congregado'), ('Discípulo(a)', 'Discípulo(a)'), ('Diácono(a)', 'Diácono(a)'), ('Missionário(a)', 'Missionário(a)'), ('Presbítero', 'Presbítero'), ('Evangelista', 'Evangelista'), ('Pastor(a)', 'Pastor(a)')], default='Membro', max_length=50),
        ),
        migrations.AddField(
            model_name='membro',
            name='data_de_nascimento',
            field=models.DateField(default='2026-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.EmailField(default='nao_informado@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='endereco',
            field=models.TextField(default='endereço não informado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_membros/'),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(default='não informado', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='congregacao', to='secretaria.area'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='secretaria.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='congregacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='secretaria.congregacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
