# Generated by Django 5.0.14 on 2026-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_congregacao_data_cadastro_membro_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitativoMembro',
            fields=[
            ],
            options={
                'verbose_name': 'Quantitativo de Membros',
                'verbose_name_plural': 'Quantitativos de Membros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('secretaria.membro',),
        ),
    ]
