# Generated by Django 5.0.14 on 2026-03-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('tesouraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesouraria.conta'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='movimento_gerado',
            field=models.BooleanField(default=False),
        ),
    ]
