# Generated by Django 5.0.14 on 2026-03-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='nome_participante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
